const DEFAULT_WAREHOUSE = 1

const ACTIVE = 1
const INACTIVE = 0
const ALREADY_EXIST = 409
const NOT_FOUND = 404
const USER_UNAUTHORIZED = 401
const SERVER_ERROR = 500
const FORBIDDEN = 403
const INVALID_PASSWORD = 406

const SUPERADMIN = 1
const ADMIN = 2
const ADMINS_MENU = 10

const CUSTOMERS = 1
const OPS = 2
const PROMO_CODES = 3
const PURCHASE_REQUESTS = 4
const ADMINSTRATION = 5

const ADMINSTRATION_USERS = [SUPERADMIN, ADMIN]

const HASHSALT = parseInt(process.env.HASH_SALT) || 10

module.exports = {
    DEFAULT_WAREHOUSE,
    ACTIVE,
    INACTIVE,
    ALREADY_EXIST,
    NOT_FOUND,
    USER_UNAUTHORIZED,
    SERVER_ERROR,
    FORBIDDEN,
    INVALID_PASSWORD,
    OPS,
    CUSTOMERS,
    PROMO_CODES,
    PURCHASE_REQUESTS,
    ADMINSTRATION,
    ADMINSTRATION_USERS,
    ADMINS_MENU,
    SUPERADMIN,
    ADMIN,
    HASHSALT
}
